pipeline {
    agent any
    tools {
        maven "mymaven"
    } 
    stages {
        stage ("code") {
            steps {
                git branch: 'main', url: 'https://github.com/suresh8972/suresh-practice.git'
            }
        }
        stage ('BUILD') {
            steps {
                dir (declarative) {
                    sh 'mvn clean package'
                }
                
            }
        }
    }
}