pipeline {
    agent any
    tools {
        maven "mymaven"
    } 
    stages {
        stage ("code") {
            steps {
                git 'https://github.com/suresh8972/suresh-practice.git'  
            }
        }
        stage ('BUILD') {
            steps {
                dir (declarative) {
                    sh 'mvn clean package'
                }
                
            }
        }
    }
}